### ISSUE TITLE
Login failed for user when using rx_exec

### ISSUE THREAD

**Issue by Sindreedelange** [kywe665/MLServicesTutorials#1]
Hi, I am trying to utilize SQL Servers new Machine Learning Services by runnning ml code directly on SQL Server, however I am currently unable to do so. Specifically I am unable to replicate your Notebook: _MLServices Remote Compute Tutorial.ipynb_ from _Define function to send to SQL Server_ and down. I get the error message:

RxInSqlServer Compute Context:
------------------------------
connection_string: "Driver={SQL Server};Server=Server_name;Database=irissql;Trusted_Connection=Yes"
num_tasks: 1
execution_timeout_seconds: 0
wait: True
console_output: False
auto_cleanup: True
packages_to_load: []
description: "sqlserver"
version: "1.0"
ImportDataSource error: Could not open data source.Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "C:\Program Files\Microsoft SQL Server\MSSQL14.DWHTEST\PYTHON_SERVICES\lib\site-packages\revoscalepy\computecontext\RxInSqlServer.py", line 643, in rx_sql_satellite_pool_call
    exec(inputfile.read())
  File "<string>", line 29, in <module>
  File "C:\Program Files\Microsoft SQL Server\MSSQL14.DWHTEST\PYTHON_SERVICES\lib\site-packages\revoscalepy\computecontext\RxInSqlServer.py", line 838, in rx_remote_call
    results = rx_resumeexecution(state_file = inputfile)
  File "C:\Program Files\Microsoft SQL Server\MSSQL14.DWHTEST\PYTHON_SERVICES\lib\site-packages\revoscalepy\computecontext\RxInSqlServer.py", line 125, in rx_resumeexecution
    return _state["function"](**_state["args"])
  File "<ipython-input-114-defc18192533>", line 16, in send_this_func_to_sql
  File "C:\Program Files\Microsoft SQL Server\MSSQL14.DWHTEST\PYTHON_SERVICES\lib\site-packages\revoscalepy\utils\RxFunctionUtils.py", line 8, in wrapper
    return func(*args,**kwds)
  File "C:\Program Files\Microsoft SQL Server\MSSQL14.DWHTEST\PYTHON_SERVICES\lib\site-packages\revoscalepy\etl\RxImport.py", line 373, in rx_import
    result = rx_native_call(functionname="ImportDataSource", params=params)
  File "C:\Program Files\Microsoft SQL Server\MSSQL14.DWHTEST\PYTHON_SERVICES\lib\site-packages\revoscalepy\RxSerializable.py", line 358, in rx_native_call
    ret = px_call(functionname, params)
RuntimeError: revoscalepy function failed.
====== ska-t-dwhdb1 ( process 0 ) has started run at 2019-02-12 10:33:12 W. Europe Standard Time ======

[Microsoft][ODBC SQL Server Driver][SQL Server]Login failed for user <username>.

[Microsoft][ODBC Driver Manager] Connection not open

ODBC Error in SQLDisconnect

Could not open data source.
ImportDataSource function failed. Please see the console output for more information.

Which I would assume means invalid connection credentials, etc., however I am able to use pyodbc to connect, and the credentials are identical. Furthermore, I am able to run functions in a sql context using, again, the same connection string. 

I am unsure what type of information you need, but the build version of the SQL Server is CU7.

**Comment by YizeD** [comment]
Not sure if you still need info on this or not as it has been 4 months, but I had a similar problem that was solved after I granted each user all permissions in the database (database-> security->user->dbo, then grant all owned schemas and membership). This is probably too blunt of a solution, as I haven't read exactly what I have granted to all the users, but it works for now.
